"use client";
import { ArrowDownUp, RefreshCw, TrendingUp, Activity } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ChartContainer, ChartTooltip } from "@/components/ui/chart";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { COMMON, NAMES, formatRate, currencyName, convertAmount, isOlderQuote, formatQuoteTime, type Currency, type Point, type PairRate } from "@/lib/fx";

export function CurrencySelect({ value, onChange, currencies, label, exclude = [] }: { value: string; onChange: (value: string) => void; currencies: Currency[]; label: string; exclude?: string[] }) {
  const options = currencies.length ? [...currencies].sort((a,b) => (COMMON.indexOf(a.code) < 0 ? 999 : COMMON.indexOf(a.code)) - (COMMON.indexOf(b.code) < 0 ? 999 : COMMON.indexOf(b.code)) || a.code.localeCompare(b.code)) : Object.keys(NAMES).map(code => ({ code, name: currencyName(code) }));
  return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="currency-select"><SelectValue>{value} · {currencyName(value)}</SelectValue></SelectTrigger><SelectContent position="popper">{options.filter(c=>!exclude.includes(c.code)).map(c => <SelectItem key={c.code} value={c.code}>{c.code} · {c.name}</SelectItem>)}</SelectContent></Select>;
}
export function PeriodSelect({days,onChange}:{days:number;onChange:(value:number)=>void}) {return <RadioGroup value={String(days)} onValueChange={v=>onChange(Number(v))} aria-label="历史时间范围" className="period-radio">{[[7,"7天"],[30,"30天"],[90,"90天"],[365,"1年"]].map(([value,label])=><label key={value} className={days===value?"active-period":""}><RadioGroupItem value={String(value)} className="sr-only"/>{label}</label>)}</RadioGroup>;}
export function Coin({ code, small = false }: { code: string; small?: boolean }) { const symbols: Record<string,string> = { USD:"$", EUR:"€", JPY:"¥", CNY:"¥", GBP:"£", KRW:"₩", CHF:"₣", INR:"₹", THB:"฿" }; return <span aria-hidden="true" className={`coin coin-${code}${small ? " small-coin" : ""}`}>{symbols[code] ?? code.slice(0,2)}</span>; }
export function Sparkline({ points, positive }: { points: Point[]; positive: boolean }) {
  if (points.length < 2) return <span className="muted">—</span>;
  const values = points.map(p => p.rate), min = Math.min(...values), range = Math.max(...values) - min || Math.max(min * .005, .000001);
  const coords = values.map((v,i) => `${3 + i/(values.length-1)*94},${31 - (v-min)/range*25}`).join(" ");
  return <svg className="sparkline" viewBox="0 0 100 38" aria-label={`${points[0].date} 至 ${points.at(-1)!.date} 的每日参考汇率走势（Frankfurter）`} role="img"><polyline points={coords} fill="none" stroke={points.at(-1)!.rate >= points[0].rate ? "#b5eb70" : "#f58e9a"} strokeWidth="1.8" strokeLinejoin="round" strokeLinecap="round"/></svg>;
}
export function Notice({ title, detail, loading = false, retry }: { title: string; detail: string; loading?: boolean; retry?: () => void }) { return <div className="empty-state" role={loading ? "status" : "alert"}>{loading ? <RefreshCw className="spin"/> : <Activity/>}<h3>{title}</h3><p>{detail}</p>{retry && <button className="button secondary" onClick={retry}>重试</button>}</div>; }
export function RateChart({ points, quote, base, loading, error, retry }: { points: Point[]; quote: string; base: string; loading: boolean; error: string; retry: () => void }) {
  if (loading) return <Notice loading title="正在获取历史走势" detail={`${quote} / ${base} · 每日参考报价`}/>;
  if (error) return <Notice title="历史走势暂不可用" detail={error} retry={retry}/>;
  if (points.length < 2) return <Notice title="历史记录不足" detail="该时段没有足够的报价，试试更长的时间范围。"/>;
  const plotted = points.map(p => ({ ...p, time: Date.parse(`${p.date}T00:00:00Z`) }));
  const min = Math.min(...points.map(p=>p.rate)), max = Math.max(...points.map(p=>p.rate)), padding = (max-min)*.15 || max*.002;
  return <><ChartContainer config={{ rate: { label: `${quote} / ${base}`, color: "#c4f76a" } }} className="history-chart" aria-label={`${quote} 兑换 ${base} 的历史汇率，${points[0].date} 至 ${points.at(-1)!.date}`}><AreaChart data={plotted} margin={{ top:12, right:8, left:0, bottom:0 }} accessibilityLayer><defs><linearGradient id="rate-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c4f76a" stopOpacity={.2}/><stop offset="100%" stopColor="#c4f76a" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#243240" strokeDasharray="3 5"/><XAxis dataKey="time" type="number" domain={["dataMin","dataMax"]} tickFormatter={v=>new Date(Number(v)).toISOString().slice(5,10)} tickLine={false} axisLine={false} minTickGap={40} tickMargin={12} fontSize={12}/><YAxis orientation="right" domain={[Math.max(0,min-padding),max+padding]} tickLine={false} axisLine={false} tickFormatter={v=>Number(v).toLocaleString("en-US",{maximumFractionDigits: v<.1?5:3})} width={64} tickMargin={8} tickCount={5} fontSize={12}/><ChartTooltip content={({active,payload})=>{ if(!active || !payload?.length) return null; const p=payload[0].payload as Point; return <div className="chart-tooltip"><span>{p.date}</span><strong>{formatRate(p.rate)} {base}</strong><small>1 {quote} 的参考价格</small></div>; }}/><Area type="linear" dataKey="rate" stroke="#c4f76a" strokeWidth={2} fill="url(#rate-fill)" isAnimationActive={false} activeDot={{ r:4, stroke:"#111923", strokeWidth:2 }}/></AreaChart></ChartContainer><div className="chart-summary"><span><TrendingUp size={14}/>区间最低 <b>{formatRate(min)}</b></span><span>区间最高 <b>{formatRate(max)}</b></span><span>{points.length} 个报价日</span></div><details className="chart-data"><summary>查看历史数据</summary><div className="history-data-scroll"><table><caption className="sr-only">每日历史参考汇率</caption><thead><tr><th>报价日期</th><th>1 {quote} = {base}</th></tr></thead><tbody>{[...points].reverse().map(p=><tr key={p.date}><td>{p.date}</td><td>{formatRate(p.rate)}</td></tr>)}</tbody></table></div></details></>;
}
export function Converter({ from, to, amount, pair, error, currencies, setFrom, setTo, setAmount, swap }: { from: string; to: string; amount: string; pair: PairRate | null; error: string; currencies: Currency[]; setFrom:(v:string)=>void; setTo:(v:string)=>void; setAmount:(v:string)=>void; swap:()=>void }) {
  const amountValue = amount.trim() === "" ? NaN : Number(amount), result = pair ? convertAmount(amountValue,pair.rate) : null;
  return <section className="panel converter-panel" id="converter"><div className="panel-heading"><h2><ArrowDownUp size={18}/>货币换算</h2></div><div className="converter-body"><label className="field-label" htmlFor="convert-amount">持有金额</label><div className="amount-input"><Input id="convert-amount" type="number" inputMode="decimal" min="0" step="any" value={amount} onChange={e=>setAmount(e.target.value)} aria-invalid={!!amount && (!Number.isFinite(amountValue) || amountValue<0)}/></div><CurrencySelect value={from} onChange={setFrom} currencies={currencies} label="持有货币"/><div className="swap-row"><span/><button className="icon-button swap-button" onClick={swap} aria-label="交换换算货币"><ArrowDownUp size={18}/></button><span/></div><span className="field-label">兑换为</span><CurrencySelect value={to} onChange={setTo} currencies={currencies} label="目标货币"/><div className="conversion-result" role="status" aria-live="polite"><span>预计可兑换</span><strong>{result === null ? "—" : result.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits: result>0&&result<.01?8:2})}<small>{to}</small></strong><p>{error || (amount && (!Number.isFinite(amountValue)||amountValue<0) ? "请输入有效的非负金额" : pair ? `1 ${from} = ${formatRate(pair.rate)} ${to}` : "正在获取换算汇率…")}</p></div><div className="conversion-note">{pair ? `${formatQuoteTime(pair.date)}${pair.frequency==="hourly"?"（北京时间）· 小时报价":" · 每日参考价"}${isOlderQuote(pair.date) ? " · 报价过期" : ""}` : "等待可用报价"}<br/>未计入兑换手续费与银行点差</div></div></section>;
}
